
-----------------------------------------------------
--[[---------------------------------------------------------------------------
DarkRP custom jobs
---------------------------------------------------------------------------

This file contains your custom jobs.
This file should also contain jobs from DarkRP that you edited.

Note: If you want to edit a default DarkRP job, first disable it in darkrp_config/disabled_defaults.lua
	Once you've done that, copy and paste the job to this file and edit it.

The default jobs can be found here:
https://github.com/FPtje/DarkRP/blob/master/gamemode/config/jobrelated.lua

For examples and explanation please visit this wiki page:
http://wiki.darkrp.com/index.php/DarkRP:CustomJobFields


Add jobs under the following line:
---------------------------------------------------------------------------]]

-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
/*--------------------------------------------------------
Default teams. If you make a team above the citizen team, people will spawn with that team!
--------------------------------------------------------*/
GAMEMODE.DefaultTeam = TEAM_CITIZEN


TEAM_CITIZEN = DarkRP.createJob("Citizen", {
    color = Color(0, 242, 53, 255),
    model = {
        "models/player/Group01/female_01.mdl",
        "models/player/Group01/female_02.mdl",
        "models/player/Group01/female_03.mdl",
        "models/player/Group01/female_04.mdl",
        "models/player/Group01/female_05.mdl",
        "models/player/Group01/male_01.mdl",
        "models/player/Group01/male_02.mdl",
        "models/player/Group01/male_03.mdl",
        "models/player/Group01/male_04.mdl",
        "models/player/Group01/male_07.mdl"
    },
    description = [[The Citizen is the most basic level of society you can hold
		besides being a hobo.
		You have no specific role in city life.]],
    weapons = {"weapons_fist"},
    command = "citizen",
    max = 0,
    salary = 100,
    admin = 0,
    vote = 0,
    hasLicense = 0,
    candemote = 0,
    category = "Citizens"
})

TEAM_POLICE = DarkRP.createJob("Police Officer", {
    color = Color(0, 10, 255, 255),
    model = {"models/player/police.mdl"},
    description = [[The protector of every citizen that lives in the city .
		You have the power to arrest criminals and protect innocents.
		Hit them with your arrest baton to put them in jail
		Bash them with a stunstick and they might learn better than to disobey
	the law.
The Battering Ram can break down 
the door of a criminal with warrant
		for his/her arrest..
	The Battering Ram can also unfreeze frozen props(if enabled).
	Type /wanted &lt;name&gt; to alert the public to this criminal
	OR go to tab and warrant someone by clicking the warrant button
	SALARY:300]],
    weapons = {"Weapons_fist", "arrest_stick", "unarrest_stick", "stunstick", "door_ram", "weaponchecker", "m9k_glock"},
    command = "CP",
    max = 4,
    salary = 300,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "Law Enforcement",
    ammo = {
        ["m9k_ammo_pistol"] = 50
    }
})

TEAM_CHIEF = DarkRP.createJob("Police Sergeant", {
    color = Color(0, 10, 255, 255),
    model = {"models/player/combine_soldier_prisonguard.mdl"},
    description = [[The Chief is the leader of the Police Officer's unit.
		Coordinate the police forces to bring law to the city
		Hit them with arrest baton to put them in jail
		Bash them with a stunstick and they might learn better than to
		disobey the law.
		The Battering Ram can break down the door of a criminal with a
		warrant for his/her arrest.
		Type /wanted &lt;name&gt; to alert the public to this criminal
		Type /jailpos to set the Jail Position
		SALARY:350]],
    weapons = {"Weapons_fist", "arrest_stick", "unarrest_stick", "m9k_deagle", "m9k_spas12", "stunstick", "door_ram", "weaponchecker"},
    command = "chief",
    max = 1,
    salary = 353,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "Law Enforcement",
    NeedToChangeFrom = TEAM_POLICE,
    ammo = {
        ["m9k_ammo_buckshot"] = 50,
        ["m9k_ammo_357"] =  50
    }
})

TEAM_MAYOR = DarkRP.createJob("The President", {
    color = Color(242, 188, 139, 255),
    model = {"models/player/donald_trump.mdl"},
    description = [[The President of BSP creates laws to serve the greater
	good of the people.
	If you are the mayor you may create and accept warrants.
	Type /wanted &lt;name&gt;  to warrant a player
	Type /jailpos to set the Jail Position
	Type /lockdown initiate a lockdown of the city.
	Everyone must be inside during a lockdown.
	The cops patrol the area
	/unlockdown to end a lockdown
	SALARY:500]],
    weapons = {"Weapons_fist", "arrest_stick", "unarrest_stick"},
    command = "GUNdealer",
    max = 1,
    salary = 500,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "Law Enforcement",
    PlayerDeath = function(ply, weapon, killer)
        ply:teamBan()
        ply:changeTeam(GAMEMODE.DefaultTeam, true)
        DarkRP.notifyAll(0, 4, "The President has died, and therefore has been demoted")
    end
})

TEAM_SS = DarkRP.createJob("Secret Service", {
    color = Color(242, 188, 139, 255),
    model = {"models/player/combine_soldier.mdl"},
    description = [[As a secret service agent, it is your job to make sure the
	mayor is safe under any Circumstances. But you are still under
	the authority of the police chief. 
	
	SALARY:350]],
    weapons = {"Weapons_fist", "m9k_m92beretta", "m9k_mp7"},
    command = "SS",
    max = 3,
    salary = 350,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "Law Enforcement",
    ammo = {
        ["m9k_ammo_smg"] = 50,
        ["m9k_ammo_pistol"] =  50
    }
})
TEAM_GUN = DarkRP.createJob("Light Weight Gun Dealer", {
    color = Color(255, 125, 0, 255),
    model = {"models/monk.mdl"},
    description = [[As a gun dealer it is your job to sell light weaponry
	to all jobs. The guns prices are at your disposal.
	
	SALARY:250]],
    weapons = {"Weapons_fist"},
    command = "GUNdealer",
    max = 3,
    salary = 250,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Dealers"
})


TEAM_HIT = DarkRP.createJob("Hit Man", {
    color = Color(186, 8, 57, 255),
    model = {"models/player/t_guerilla.mdl"},
    description = [[As a hit man its your job to kill the players
	that have a "hit" on them.
	
	SALARYL:250]],
    weapons = {"weapon_fists", "m9k_contender"},
    command = "Hitman",
    max = 1,
    salary = 220,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Crime",
    ammo = {
        ["m9k_ammo_sniper_rounds"] = 100
    }
})

TEAM_FIGHT = DarkRP.createJob("Fight Club Manager", {
    color = Color(207, 96, 127, 255),
    model = {"models/Humans/Group01/Male_Cheaple.mdl"},
    description = [[As a fight club manager you can set up your fight club
	on any state you buy. Both players must agree to the fight clubs terms
	before any pvp fights occur.
	
	SALARYL:220]],
    weapons = {"weapon_fists", "weapon_bugbait"},
    command = "fight",
    max = 1,
    salary = 220,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Citizen"
})

TEAM_HOBO = DarkRP.createJob("Hobo", {
    color = Color(128, 90, 34, 255),
    model = {"models/player/corpse1.mdl"},
    description = [[The lowest member of society. All people see you laugh.
		You have no home.
		Beg for your food and money
		Sing for everyone who passes to get money
		Make your own wooden home somewhere in a corner or
		outside someone else's door
		SALARY:0]],
    weapons = {"weapon_fists", "weapon_bugbait"},
    command = "hobo",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Citizen"
})

TEAM_BODYGUARD = DarkRP.createJob("Body Guard", {
    color = Color(170, 222, 143, 255),
    model = {"models/player/odessa.mdl"},
    description = [[As a bodyguard it is you duty to protect you employer and his estate

            Salary: 250]],
    weapons = {"weapon_fists", "m9k_usp"},
    command = "bodyguard",
    max = 3,
    salary = 250,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizen",
    ammo = {
        ["m9k_ammo_pistol"] = 100
    }
})

TEAM_THIEF = DarkRP.createJob("Thief", {
    color = Color(145, 142, 142, 255),
    model = {"models/player/arctic.mdl"},
    description = [[ Your are a thief, breaking into peoples homes, and business's is a everyday normal task for you.
You take what you want.
You may not shoot people in there own only in robbery.
homes or places of business. only in robbery.
to shoot you!. 
	SALARY:170]],
    weapons = {"lockpick", "keypad_cracker"},
    command = "Thief",
    max = 4,
    salary = 170,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Crime"
})
TEAM_HOTEL = DarkRP.createJob("Hotel Manager", {
    color = Color(201, 140, 140, 255),
    model = {"models/player/Group01/male_08.mdl"},
    description = [[ As a Hotel Manager you are responsible for renting rooms and maintaining them.  
       Salary= 250]],
    weapons = {"stunstick"},
    command = "Hotel",
    max = 1,
    salary = 250,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens"
})
TEAM_BloodL = DarkRP.createJob("Crenshaw Bloods Leader", {
    color = Color(252, 0, 0, 255),
    model = {"models/ls/player/bloodz/slow_1.mdl"},
    description = [[You are the leader of the Crenshaw Bloods, You will give orders to your gang and declare gang wars.
	
	SALARY:350]],
    weapons = {"unarrest_stick", "lockpick"},
    command = "BloodL",
    max = 1,
    salary = 350,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Crime"
})

TEAM_Blood = DarkRP.createJob("Crenshaw Bloods Member", {
    color = Color(252, 0, 0, 255),
    model = {
        "models/ls/player/bloodz/slow_2.mdl",
        "models/ls/player/bloodz/slow_3.mdl"
    },
    description = [[You are a Crenshaw Blood, you follow your OG's orders
You are sworn enemies with the Crips, but you cannot KOS them without
War being declared and agreed upon both sides in advert
	
	SALARY:200]],
    weapons = {},
    command = "Blood",
    max = 5,
    salary = 200,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Crime"
})

TEAM_CripL = DarkRP.createJob("Hoover Crips Leader", {
    color = Color(0, 71, 255, 255),
    model = {"bandc/models/player/cripz/slow_1.mdl"},
    description = [[[As the leader of the Hoover Crips you will give orders to your gang and declare gang wars.
	
	SALARY:450]],
    weapons = {"unarrest_stick", "weapon_fists", "lockpick"},
    command = "CRIPL",
    max = 1,
    salary = 450,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Crime"
})

TEAM_Crip = DarkRP.createJob("Hoover Crip Member", {
    color = Color(0, 71, 255, 255),
    model = {
        "bandc/models/player/cripz/slow_2.mdl",
        "bandc/models/player/cripz/slow_3.mdl"
    },
    description = [[You are a Hoover Crip, you follow your OG's orders
You are sworn enemies with the Bloods, but you cannot KOS them without
War being declared and agreed upon both sides in advert
	SALARY:120]],
    weapons = {"weapon_fists"},
    command = "CRIP",
    max = 5,
    salary = 200,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Crime"
})

TEAM_SWAT = DarkRP.createJob("S.W.A.T.", {
    color = Color(0, 71, 255, 255),
    model = {"models/player/urban.mdl"},
    description = [[ As a S.W.A.T officer it is your job to infiltrate
drug labs and gang operations, to assist your fellow police officers on high level raids.
	You are under the authority of the police chief. 
	
	SALARY:350]],
    weapons = {"m9k_mp5", "arrest_stick", "weapon_fists", "door_ram", "stunstick", "unarrest_stick", "weaponchecker", "m9k_hk45"},
    command = "SWAT",
    max = 3,
    salary = 350,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "Law Enforcement",
    NeedToChangeFrom = TEAM_POLICE,
    ammo = {
        ["m9k_ammo_smg"] = 200,
        ["m9k_ammo_pistol"] =  200
    }
})
TEAM_FBI = DarkRP.createJob("F.B.I.", {
    color = Color(214, 255, 0, 255),
    model = {"models/player/riot.mdl"},
    description = [[ As an F.B.I. member you are responsible for tracking and shutting down massive
	gang operations, and terrorist plots.
	
	SALARY:500]],
    weapons = {"weaponchecker", "arrest_stick", "weapon_fists", "unarrest_stick", "stungun", "keys", "m9k_sig_p229r"},
    command = "fbi",
    max = 3,
    salary = 500,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "Law Enforcement",
    ammo = {
        ["m9k_ammo_pistol"] = 300
    }
})

[[---------------------VIP------------]]
TEAM_NG = DarkRP.createJob("National Guard", {
    color = Color(214, 255, 0, 255),
    model = {"models/player/dod_american.mdl"},
    description = [[ [VIP] As a member of the National Guard
	your job is to protect the citizen from terrorist...
	If its allot of Terrorists in the city the Lieutenant Colonel of the
	National Guard is in charge over all Law Enforcement in the city.
	
	SALARY:500]],
    weapons = {"weaponchecker", "m9k_m92beretta", "weapon_fists", "arrest_stick", "unarrest_stick", "stungun", "keys", "m9k_scar"},
    command = "ninja",
    max = 3,
    salary = 700,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "VIP",
    ammo = {
        ["m9k_ammo_ar2"] = 300,
        ["m9k_ammo_pistol"] =  300
    },
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
        ply:SetBodygroup(0, 0)
    end,
    customCheck = function(ply) return CLIENT or
        table.HasValue({"superadmin", "owner", "admin", "VIP+", "DONORMOD", "MOD", "VIP"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must donate for VIP, or VIP+ or donor-mod to play this job",
})

TEAM_NINJA = DarkRP.createJob("Ninja", {
    color = Color(214, 255, 0, 255),
    model = {"models/player/charple.mdl"},
    description = [[ [[VIP]]As a ninja you can jump from building to building with your grappling hook,
	while slaying every person that comes at you sideways with a pure Damascus steel katana.
	
	SALARY:600]],
    weapons = {"m9k_damascus", "weapon_fists", },
    command = "ninja",
    max = 3,
    salary = 700,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "VIP",
 
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
        ply:SetBodygroup(0, 0)
    end,
    customCheck = function(ply) return CLIENT or
        table.HasValue({"superadmin", "owner", "admin", "VIP+", "DONORMOD", "MOD", "VIP"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must donate for VIP, or VIP+ or donor-mod to play this job",
})

TEAM_BANK = DarkRP.createJob("Downtown Bank Owner", {
    color = Color(214, 255, 0, 255),
    model = {"models/player/Hostage/hostage_04.mdl"},
    description = [[ [VIP] As a Bank Owner you can store
	printers, guns , and other paraphernalia for other players at a price.
[[Bank Owner's CANNOT be arrested for the possession of any body else's printers or guns.]]
	
	SALARY:200]],
    weapons = {"weapon_fists"},
    command = "bank",
    max = 1,
    salary = 200,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "VIP",
    customCheck = function(ply) return CLIENT or
        table.HasValue({"superadmin", "owner", "admin", "VIP+", "DONORMOD", "MOD", "VIP"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must donate for VIP to play this job!",
})

TEAM_PROTHIEF = DarkRP.createJob("Pro Thief", {
    color = Color(145, 142, 142, 255),
    model = {"models/player/arctic.mdl"},
    description = [[ [VIP]Your are a pro thief, breaking into peoples homes, and business's is a everyday normal task for you.
You take what you want.
You may not shoot people in there own only in robbery.
homes or places of business. only in robbery.
to shoot you!. 
	SALARY:900]],
    weapons = {"pro_lockpick", "weapon_fists",  "prokeypadcracker", "M9k_scar"},
    command = "Prothief",
    max = 2,
    salary = 900,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Crime",
    ammo = {
        ["m9k_ammo_assault"] = 200
    },
    PlayerSpawn = function(ply)
        ply:SetArmor(50)
    end,
    customCheck = function(ply) return CLIENT or
        table.HasValue({"Owner", "superadmin", "admin", "mod", "VIP+", "VIP", "DonorMod"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must donate for VIP to play this job!",
})

[[--------------VIP+--------------]]
TEAM_NGLT = DarkRP.createJob("National Guard Lieutenant Colonel", {
    color = Color(34, 51, 85, 255),
    model = {"models/player/dod_german.mdl"},
    description = [VIP+ Job] As the Lieutenant Colonel in the
	National Guard its your job to be in charge of all Law Enforcement
	when its alot of terrorists or attacks in the city.]],
    weapons = {"weaponchecker", "m9k_m249lmg", "m9k_m92beretta", "weapon_fists", "arrest_stick", "unarrest_stick", "stungun", "keys"},
    command = "nglt",
    max = 1,
    salary = 700,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "VIP+",
    ammo = {
        ["m9k_ammo_ar2"] = 300,
        ["m9k_ammo_pistol"] =  300
    },
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
        ply:SetBodygroup(0, 0)
    end,
    PlayerDeath = function(ply, weapon, killer)
        ply:teamBan()
        ply:changeTeam(GAMEMODE.DefaultTeam, true)
        DarkRP.notifyAll(0, 4, "The Lieutenant Colonel has died, therefore he has been demoted.")
    end,
    customCheck = function(ply) return CLIENT or
        table.HasValue({"superadmin", "owner", "admin", "VIP+", "DONORMOD", "MOD"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must donate for VIP+, or donor-mod to play this job",
})

TEAM_PROTHIEF = DarkRP.createJob("Pro Thief", {
    color = Color(145, 142, 142, 255),
    model = {"models/player/arctic.mdl"},
    description = [[ [VIP]Your are a pro thief, breaking into peoples homes, and business's is a everyday normal task for you.
You take what you want.
You may not shoot people in there own only in robbery.
homes or places of business. only in robbery.
to shoot you!. 
	SALARY:900]],
    weapons = {"pro_lockpick", "weapon_fists",  "prokeypadcracker", "M9k_scar"},
    command = "Prothief",
    max = 2,
    salary = 900,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Crime",
    ammo = {
        ["m9k_ammo_assault"] = 200
    },
    PlayerSpawn = function(ply)
        ply:SetArmor(50)
    end,
    customCheck = function(ply) return CLIENT or
        table.HasValue({"Owner", "superadmin", "admin", "mod", "VIP+", "VIP", "DonorMod"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must donate for VIP to play this job!",
})
TEAM_BOUNTY = DarkRP.createJob("Bounty Hunter", {
    color = Color(186, 8, 57, 255),
    model = {"models/player/starwars/b4p_bobafett.mdl"},
    description = [[[ [VIP+] As a bounty hunter its your job to find wanted players and
	take them down to the station.
	
	SALARYL:1400]],
    weapons = {"weapon_fists", "m9k_contender", "m9k_mp7"},
    command = "Hitman",
    max = 2,
    salary = 1400,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Crime",
    ammo = {
        ["m9k_ammo_sniper_rounds"] = 100,
        ["m9k_ammo_smg"] =  200
    },
    PlayerSpawn = function(ply)
        ply:SetArmor(100)
    end,
    customCheck = function(ply) return CLIENT or
        table.HasValue({}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must donate for VIP to play this job!",
})

TEAM_SWATCO = DarkRP.createJob("S.W.A.T. Commander", {
    color = Color(0, 10, 255, 255),
    model = {"models/player/urban.mdl"},
    description = [[ [VIP+ Job] As a S.W.A.T Commander it is your
	job to infiltrate drug labs and and assist other law enforcement officers on high level raids.
	You are also still under the authority of the Police Chief!

Salary:700]],
    weapons = {"arrest_stick", "unarrest_stick", "stunstick", "door_ram", "weaponchecker", "m9k_m16a4_acog", "weapon_fists", "m9k_ragingbull"},
    command = "SWATCO",
    max = 1,
    salary = 700,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true,
    category = "VIP+",
    ammo = {
        ["m9k_ammo_357"] = 200,
        ["m9k_ammo_ar2"] =  200
    },
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(50)
    end,
    customCheck = function(ply) return CLIENT or
        table.HasValue({"superadmin", "owner", "admin", "VIP+", "DONORMOD", "MOD"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must donate for VIP to play this job!",
})
[[----------------STAFF--------]]

TEAM_OWNER = DarkRP.createJob("Owner On Duty", {
    color = Color(51, 0, 255, 255),
    model = {
        "models/overwatch/characters/hanzo_default.mdl",
        "models/bender/bender.mdl"
    },
    description = [[OWNER]] This class is for the man himself

]],
    weapons = {"m9k_minigun", "weapons_fist" },
    command = "Owner",
    max = 1,
    salary = 700,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Staff",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(10000)
    end,
    customCheck = function(ply) return
        table.HasValue({"owner"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must be Beeg Schmoze Himself to play this job.",
})

TEAM_Sadmin = DarkRP.createJob("Super Admin on duty", {
    color = Color(51, 0, 255, 255),
    model = {"models/player/chewie.mdl"},
    description = [[SUPERADMIN]] This class is for the highest ranking of my staff

]],
    weapons = {},
    command = "Sadmin",
    max = 0,
    salary = 700,
    admin = 2,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Staff",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(10000)
    end
})

TEAM_admin = DarkRP.createJob("Admin on duty", {
    color = Color(0, 240, 255, 255),
    model = {"models/player/combine_super_soldier.mdl"},
    description = [[ADMIN]] This class is for Admins on duty

]],
    weapons = {"weapon_fists"},
    command = "admin",
    max = 0,
    salary = 700,
    admin = 1,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Staff",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(10000)
    end
})

TEAM_MOD = DarkRP.createJob("Mod on Duty", {
    color = Color(0, 240, 255, 255),
    model = {"models/player/combine_super_soldier.mdl"},
    description = [[MOD]] This class is for Moderators on duty

]],
    weapons = {"weapon_fists"},
    command = "Mod",
    max = 0,
    salary = 700,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Staff",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(10000)
    end,
    customCheck = function(ply) return
        table.HasValue({"owner", "mod", "admin", "superadmin"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must be a Moderator to play this job.",
})

TEAM_DONORMOD = DarkRP.createJob("Donor Mod on Duty", {
    color = Color(0, 240, 255, 255),
    model = {"models/player/john_marston.mdl"},
    description = [[DONOR MOD]] This class is for Donor Mods on duty

]],
    weapons = {"weapon_fists"},
    command = "Sadmin",
    max = 0,
    salary = 700,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Staff",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(10000)
    end,
    customCheck = function(ply) return
        table.HasValue({"owner", "mod", "admin", "superadmin", "donormod"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "You must be Beeg Schmoze Himself to play this job.",
})
-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1
TEAM_COOK    = TEAM_COOK     or -1

-- Door groups
DarkRP.createEntityGroup("Law enforcement only!", TEAM_POLICE, TEAM_MAYOR, TEAM_SWAT, TEAM_SWATCO, TEAM_SS, TEAM_NGLT, TEAM_NG, TEAM_FBI, TEAM_CHIEF)


-- Agendas
DarkRP.createAgenda("Bloods Agenda", {TEAM_BLOODL}, {TEAM_BLOOD})
DarkRP.createAgenda("Law Enforcement Agenda", {TEAM_MAYOR}, {TEAM_POLICE, TEAM_SWAT, TEAM_SWATCO, TEAM_SS, TEAM_NGLT, TEAM_NG, TEAM_FBI, TEAM_CHIEF})
DarkRP.createAgenda("Crips Agenda", {TEAM_CRIPL}, {TEAM_CRIP})
-- Group chats
DarkRP.createGroupChat(TEAM_POLICE, TEAM_MAYOR, TEAM_SWAT, TEAM_SWATCO, TEAM_SS, TEAM_NGLT, TEAM_NG, TEAM_FBI, TEAM_CHIEF)
DarkRP.createGroupChat(TEAM_BLOODL, TEAM_BLOOD)
DarkRP.createGroupChat(TEAM_CRIPL, TEAM_CRIP)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)

-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_CITIZEN

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_CHIEF] = true,
    [TEAM_MAYOR] = true,
	[TEAM_SWAT] = true,
	[TEAM_SWATCO] = true,
	[TEAM_SS] = true,
	[TEAM_NG] = true,
	[TEAM_NGLT] = true,
	[TEAM_FBI] = true,
}

-- Hitman team
DarkRP.addHitmanTeam(TEAM_HIT)
DarkRP.addHitmanTeam(TEAM_BOUNTY)

-- Demote groups
DarkRP.createDemoteGroup("Law Enforcement", {TEAM_POLICE, TEAM_MAYOR, TEAM_SWAT, TEAM_SWATCO, TEAM_SS, TEAM_NGLT, TEAM_NG, TEAM_FBI, TEAM_CHIEF})
DarkRP.createDemoteGroup("Gangs", {TEAM_BLOODL, TEAM_BLOOD, TEAM_CRIP, TEAM_CRIPL})
DarkRP.createDemoteGroup("Hit men", {TEAM_HIT, TEAM_BOUNTY})
-- Default categories
DarkRP.createCategory{
    name = "Citizens",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 100,
}

DarkRP.createCategory{
    name = "Civil Protection",
    categorises = "jobs",
    startExpanded = true,
    color = Color(25, 25, 170, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 101,
}

DarkRP.createCategory{
    name = "Gangsters",
    categorises = "jobs",
    startExpanded = true,
    color = Color(75, 75, 75, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 101,
}

DarkRP.createCategory{
    name = "Other",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}
